-- =============================================================
-- Sistema de Balance — Don Chacho
-- Módulo de SOPORTE: el cliente reporta problemas desde la app.
--
-- Antes los problemas llegaban suelto por WhatsApp ("no me anda algo"),
-- sin módulo, sin fecha, sin versión y sin captura. Ahora cada reclamo
-- queda registrado acá con todo el contexto que la app puede capturar sola.
--
-- WhatsApp sigue existiendo, pero SOLO como aviso: la fuente de la verdad
-- es esta tabla y el reclamo queda guardado aunque el mensaje nunca se
-- mande.
--
-- Idempotente.
-- =============================================================

-- -------------------------------------------------------------
-- 1. Tabla
-- -------------------------------------------------------------
-- `numero` es IDENTITY a propósito: el número de ticket (S-0001) lo asigna
-- la secuencia de Postgres y no el cliente. El resto del proyecto numera
-- algunas entidades con max+1 del lado del cliente; acá no, porque dos
-- personas reportando a la vez se pisarían. La app omite el campo en el
-- insert y recupera la fila (`.select().single()`) para leer el número que
-- le tocó.
create table if not exists soportes (
  id            uuid primary key default gen_random_uuid(),
  numero        int generated by default as identity,
  modulo        text not null default '',
  descripcion   text not null default '',
  bloqueante    boolean not null default false,
  -- PATH del archivo en el bucket, nunca la URL: los links se firman en el
  -- momento (ver el comentario del bucket más abajo).
  adjunto_path  text,
  estado        text not null default 'abierto'
    check (estado in ('abierto', 'en_revision', 'resuelto')),
  respuesta     text default '',
  -- Contexto que captura la app sola, sin preguntarle nada al usuario.
  reportado_por text,
  rol           text,
  app_version   text,
  plataforma    text,
  creado_en     timestamptz not null default now(),
  resuelto_en   timestamptz,
  resuelto_por  text
);

-- La bandeja filtra por estado (3 tabs) y ordena por fecha desc.
create index if not exists idx_soportes_estado on soportes (estado);
create index if not exists idx_soportes_creado on soportes (creado_en desc);

-- -------------------------------------------------------------
-- 2. RLS
-- -------------------------------------------------------------
alter table soportes enable row level security;

-- Reportar un problema NO se gatea con permisos: justamente el caso que
-- importa es el de alguien que no puede trabajar porque no tiene acceso a
-- algo. Cualquier usuario con sesión puede insertar.
--
-- `to authenticated` (y no el `to public` implícito de las políticas más
-- viejas del proyecto) porque la condición es `true`: sin el `to`, cualquiera
-- con la anon key —que es pública, va compilada en el bundle web— podría
-- llenar la tabla de basura.
drop policy if exists "autenticado reporta soporte" on soportes;
create policy "autenticado reporta soporte" on soportes for insert
  to authenticated
  with check (true);

-- Lectura para cualquier usuario con sesión. "Tus reclamos" filtra por
-- `reportado_por` en el cliente, no en la política: la columna es texto libre
-- (el nombre del perfil) y no hay forma de atarla a `auth.uid()` sin agregar
-- una columna que el esquema de origen no tiene. En un deploy de dos personas
-- —admin y cajera— el dato que se expondría es la descripción que la otra
-- escribió, no datos de clientes: esos están en las capturas, y el bucket sí
-- queda privado.
drop policy if exists "autenticado lee soportes" on soportes;
create policy "autenticado lee soportes" on soportes for select
  to authenticated
  using (true);

-- Triage: cambiar estado y escribir la respuesta es solo del admin.
-- Sin esta restricción la cajera podría cerrarse sus propios reclamos.
drop policy if exists "admin resuelve soportes" on soportes;
create policy "admin resuelve soportes" on soportes for update
  to authenticated
  using      (is_admin())
  with check (is_admin());

-- A propósito no hay política de DELETE: los reclamos no se borran, se
-- resuelven. Queda el historial.

-- -------------------------------------------------------------
-- 3. Bucket de adjuntos
-- -------------------------------------------------------------
-- PRIVADO: las capturas de pantalla muestran ventas, compras y gastos de las
-- sucursales. Los links se firman al momento de usarlos, con vigencia 90
-- días, así el link que se reenvió por WhatsApp caduca solo mientras la
-- bandeja siempre puede firmar uno nuevo.
--
-- Los HEIC/HEIF están permitidos porque las fotos de iPhone llegan en ese
-- formato. El navegador no las renderiza, pero el archivo tiene que poder
-- subirse igual (la bandeja ofrece abrirlo aparte).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('soporte-adjuntos', 'soporte-adjuntos', false, 10485760,
        array['image/jpeg','image/png','image/webp','image/heic','image/heif'])
on conflict (id) do nothing;

-- Policies de storage para el rol con el que trabaja la app.
--
-- El módulo original corría con la publishable key sin sesión, o sea rol
-- `anon`. En ESTE proyecto el router obliga a loguearse antes de llegar a
-- cualquier pantalla, así que el JWT siempre trae rol `authenticated` y
-- alcanza con dárselas a ese rol: `anon` quedaría abierto a cualquiera que
-- tenga la anon key del bundle.
--
-- Hacen falta INSERT y SELECT. El SELECT no es para leer el archivo directo:
-- sin él `createSignedUrl` falla, y la bandeja se queda sin poder mostrar la
-- captura.
drop policy if exists "soporte_adjuntos_insert" on storage.objects;
create policy "soporte_adjuntos_insert" on storage.objects for insert
  to authenticated
  with check (bucket_id = 'soporte-adjuntos');

drop policy if exists "soporte_adjuntos_select" on storage.objects;
create policy "soporte_adjuntos_select" on storage.objects for select
  to authenticated
  using (bucket_id = 'soporte-adjuntos');
